name: lib-ledger-core CI

on:
    push:
        path:
            - '**.cpp'
            - '**.hpp'
    pull_request:
        path:
            - '**.cpp'
            - '**.hpp'

jobs:
    prepare-linux-debug:
        runs-on: ubuntu-latest
        steps:
          - name: Install dependencies
            shell: bash
            run: |
              chmod +x ./scripts/install_dependencies.sh
              bash ./scripts/install_dependencies.sh Linux Debug
          - uses: actions/checkout@v2
          - name: Checkout submodules
            shell: bash
            run: ./scripts/checkout_submodule.sh

    build-linux-debug-core:
        runs-on: ubuntu-latest
        needs: prepare-linux-debug
        steps:
          - name: Generate interfaces
            shell: bash
            run: ./tools/lc api
          - name: CMake configuration
            shell: bash
            run: ./scripts/cmake_configuration.sh Linux Debug
          - name: Build target
            run: cd ledger-core/build && make -j8
          - name: Install target
            run: cd ledger-core/build && make install

    test-linux-debug-core:
        runs-on: ubuntu-latest
        needs: build-linux-debug-core
        steps:
          - name: Test target
            run: cd ledger-core/build/ && make test
