name: lib-ledger-core CI

on:
    push:
        path:
            - '**.cpp'
            - '**.hpp'
    pull_request:
        path:
            - '**.cpp'
            - '**.hpp'

jobs:
    build-linux-debug:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          # - name: Install dependencies
          #   run: |
          #     sudo apt-get install -y libx11-xcb-dev libssl-dev tcl
          #     sudo apt-get install -y qt5-default libqt5websockets5 libqt5websockets5-dev
          #     sudo apt-get install -y slqlite3 sqlite libsqlit3-dev
          - name: Checkout submodules
            run: |
              git submodule init
              git submodule update --recursive
          - name: Generate interfaces
            shell: bash
            run: ./tools/lc api
          - name: Create build directory
            run: mkdir -p ledger-core/build
          - name: Configure CMake
            working-directory: ledger-core/build
            run: cmake -DCMAKE_BUILD_TYPE=Debug -DPG_SUPPORT=ON -DCMAKE_INSTALL_PREFIX=../../install -DSYS_OPENSSL=ON -DOPENSSL_SSL_LIBRARIES=/usr/lib/x86_64-linux-gnu -DOPENSSL_INCLUDE_DIR=/usr/include/openssl ..
          - name: Build ledger-core
            working-directory: ledger-core/build
            run: make -j8
          - name: Create install directory
            run: mkdir -p install
          - name: Install ledger-core
            working-directory: ledger-core/build
            run: make install

