name: Continuous integration

on:
    push:
        path:
          - '**.cpp'
          - '**.hpp'
    pull_request:
        path:
          - '**.cpp'
          - '**.hpp'

jobs:
    build:
      name: Build ${{ matrix.os.alias }} target in ${{ matrix.mode }} mode
      strategy:
        fail-fast: false
        matrix:
          os: [
            { name: ubuntu-latest, alias: Linux },
            { name: macOS-latest, alias: Macos },
            { name: windows-latest, alias: Windows }
          ]
          mode: [Debug]
      runs-on: ${{ matrix.os.name }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Install dependencies
          shell: bash
          run: scripts/install_dependencies.sh ${{ matrix.os.alias }} ${{ matrix.mode }}
        - name: Checkout submodules
          run: |
            git submodule init
            git submodule update --recursive
        - name: Generate interfaces
          shell: bash
          run: tools/lc api
        - name: Configure CMake
          shell: bash
          run: scripts/configure_cmake.sh ${{ matrix.os.alias }} ${{ matrix.mode }}
        - name: Build ledger-core
          working-directory: ledger-core/build
          run: make -j8
        - name: Install ledger-core
          working-directory: ledger-core/build
          run: make install
        - name: Test ledger-core
          working-directory: ledger-core/build
          run: make test

