name: lib-ledger-core CI

on:
    push:
        path:
            - '**.cpp'
            - '**.hpp'
    pull_request:
        path:
            - '**.cpp'
            - '**.hpp'

jobs:
    build-linux-debug-core:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Install dependencies
            shell: bash
            run: ./scripts/install_dependencies.sh Linux Debug
          - name: Checkout submodules
            shell: bash
            run: ./scripts/checkout_submodule.sh
          - name: Generate interfaces
            shell: bash
            run: ./tools/lc api
          - name: CMake configuration
            shell: bash
            run: ./scripts/cmake_configuration.sh Linux Debug
          - name: Build target
            working-directory: ./ledger-core/build
            run: make -j8
          - name: Install target
            working-directory: ./ledger-core/build
            run: make install
          - name: Upload install directory
            uses: actions/upload-artifact@v1
            with:
              name: install
              path: ./install

    build-linux-debug-bitcoin:
        runs-on: ubuntu-latest
        needs: build-linux-debug-core
        steps:
          - name: Download install directory
            uses: actions/download-artifact@v1
            with:
              name: install
